services:
  gateway:
    build:
      context: .
      network: host
    image: gateway
    container_name: gateway-container
    working_dir: /app
    command: /app/.venv/bin/uvicorn backend.main:app --reload --host 0.0.0.0 --port 8080
    ports:
      - "8080:8080"
    dns:
      - 1.1.1.1   # Cloudflare
      - 9.9.9.9   # Quad9
    # oder: euer lokaler DNS (z. B. 192.168.178.1), falls öffentliche blockiert sind
      - 192.168.178.1
    extra_hosts:
      - "api.getzep.com:172.66.40.150"
    volumes:
      - ./backend:/app/backend
      - ./utils:/app/utils
      - ./src:/app/src
      - ./config:/app/config:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - gateway-net
    environment:
      OPENAI_API_KEY: "${OPENAI_API_KEY}"
      OPENAI_MODEL: gpt-4o-mini  
      OPENAI_PROJECT_ID: "${OPENAI_PROJECT_ID}"
      OPENAI_ORG_ID: "${OPENAI_ORG_ID}"
      PYTHONPATH: "/app"
      GATEWAY_API_URL: "http://gateway:8080/api/chat"
      # OPTIONAL, wenn du ein OpenAI-kompatibles Gateway nutzt (LM Studio, OpenRouter, o.ä.):
      # OPENAI_BASE_URL: https://api.openai.com/v1
      LLM_DEBUG: "1"   

    env_file:
      - .env
    restart: no

networks:
  gateway-net:
    driver: bridge
    
volumes:                   
  zep_state: {}  